config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :recipes
  resources :ingredients

   root 'pages#home'
   get 'pages/about'

   get '/search', to: 'recipes#search'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_and_belongs_to_many :recipes
  validates :item_id, presence: true
  validates :name, presence: true, uniqueness: true

  require "nutritionix/api_1_1"

  def provider
    app_id = Figaro.env.nutritionix_app_id
    app_key = Figaro.env.nutritionix_app_key
    Nutritionix::Api_1_1.new(app_id, app_key)
  end


  def ingredient_search(query)

  #  app_id = Figaro.env.nutritionix_app_id
  #  app_key = Figaro.env.nutritionix_app_key
  #  provider = Nutritionix::Api_1_1.new(app_id, app_key)

    search_params = {
      offset: 0,
      limit: 10,
      fields: ['item_id', 'item_description', 'item_name', 'nf_calories'],
      filters: {
        item_type: 3 #filters results for only USDA listing
      },
      query: query
    }

    results_json = provider.nxql_search(search_params)
    JSON.parse(results_json)
  end

  def filtered_search(params)
    hash = ingredient_search(params[:keyword]) # Get the full hash
    if hash.key?("hits")
       hash.fetch("hits") # Fetch Hits
    end
  end

  def get_item(id)
    results_json = provider.get_item(id)
    hash = JSON.parse(results_json)
    if hash.nil?
      { }
    elsif hash.has_key?("error")
      { }
    else
      hash
    end
  end


end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show]

  respond_to :html, :js

  def index
    @ingredients = Ingredient.all
    respond_with(@ingredients)
  end

  def show
    @facts = @ingredient.get_item(@ingredient.item_id)
    respond_with(@ingredient)
  end

  def new
    @ingredient = Ingredient.new
    @results = @ingredient.filtered_search(params)
    respond_with(@ingredient)
  end

  def edit
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.save
    respond_with(@ingredient)
  end

  def update
    @ingredient.update(ingredient_params)
    respond_with(@ingredient)
  end

  def destroy
    @ingredient.destroy
    respond_with(@ingredient)
  end

  private
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
      params.require(:ingredient).permit(:name, :body, :item_id)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/_nutrition.html.erb
<section class="nutrition-facts">
  <header class="nutrition-header">
    <h1 class="nutrition-title"><%= @ingredient.name %> Nutrition Facts</h1>
    <p>Serving Size: <%= @facts["nf_serving_size_qty"] %> <%= @facts["nf_serving_size_unit"] %>
    </header>
    <table class="nutrition-table">
      <thead>
        <tr>
          <th colspan="3" class="small-info">
            Amount Per Serving
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th colspan="2">
            <b>Calories</b>
            <%= @facts["nf_calories"].round(2) %>
          </th>
          <td>
            Calories from Fat
            <%= @facts["nf_calories_from_fat"].round(0) %>
          </td>
        </tr>
        <tr class="thick-row">
          <td colspan="3" class="small-info">
            <b>% Daily Value*</b>
          </td>
        </tr>
        <tr>
          <th colspan="2">
            <b>Total Fat</b>
            <%= @facts["nf_total_fat"].round(2) %>g
          </th>
          <td>
            <b><%= ((@facts["nf_total_fat"] /65)*100).round(2) %>%</b>
          </td>
        </tr>
        <tr>
          <td class="blank-cell">
          </td>
          <th>
            Saturated Fat
            <%= @facts["nf_saturated_fat"].round(2) %>g
          </th>
          <td>
          </td>
        </tr>
        <tr>
          <td class="blank-cell">
          </td>
          <th>
            Polyunsaturated Fat
            <%= @facts["nf_polyunsaturated_fat"].round(2) %>g
          </th>
          <td>
          </td>
        </tr>
        <tr>
          <th colspan="2">
            <b>Cholesterol</b>
            <%= @facts["nf_cholesterol"].round(2) %>mg
          </th>
          <td>
          </td>
        </tr>
        <tr>
          <th colspan="2">
            <b>Sodium</b>
            <%= @facts["nf_sodium"].round(2) %>mg
          </th>
          <td>
          </td>
        </tr>
        <tr>
          <th colspan="2">
            <b>Total Carbohydrate</b>
            <%= @facts["nf_total_carbohydrate"].round(2) %>g
          </th>
          <td>
          </td>
        </tr>
        <tr>
          <td class="blank-cell">
          </td>
          <th>
            Dietary Fiber
            <%= @facts["nf_dietary_fiber"].round(2) %>g
          </th>
          <td>
          </td>
        </tr>
        <tr>
          <td class="blank-cell">
          </td>
          <th>
            Sugars
            <%= @facts["nf_sugars"].round(2) %>g
          </th>
          <td>
          </td>
        </tr>
        <tr class="thick-end">
          <th colspan="2">
            <b>Protein</b>
            <%= @facts["nf_protein"].round(2) %>g
          </th>
          <td>
          </td>
        </tr>
      </tbody>
    </table>

    <table class="small-table">
      <tbody>
        <tr>
          <td colspan="2">
            Vitamin A
            <%= @facts["nf_vitamin_a_dv"] %>%
          </td>
          <td>
            Vitamin C
            <%= @facts["nf_vitamin_c_dv"] %>%
          </td>
        </tr>
        <tr class="thin-end">
          <td colspan="2">
            Calcium
            <%= @facts["nf_calcium_dv"] %>%
          </td>
          <td>
            Iron
            <%= @facts["nf_iron_dv"] %>%
          </td>
        </tr>
      </tbody>
    </table>
  </section>

app/views/ingredients/edit.html.erb
<% content_for :title, "Edit Ingredient" %>
<h1>Editing Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<% content_for :title, "All Ingredients" %>

<p id="notice"><%= notice %></p>

<h1>Listing Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Item ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.body %></td>
        <td><%= ingredient.item_id %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<% content_for :title, "Find New Ingredients" %>

<h2>Find New Ingredients</h2>

<div class="fields">
  <%= form_tag(new_ingredient_path, method: :get, remote: true ) do %>
  <%= text_field_tag :keyword, nil, placeholder: "Find More Ingredients..." %>
  <%= submit_tag "Find Ingredients", class: "button-default", id: "ingredient-search" %>
  <% end %>
</div>

<div class="results"></div>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/new.js.erb
$(".results").html("<%= escape_javascript(render 'layouts/ingredient_search' ) %>");

app/views/ingredients/search.html.erb
<% content_for :title, "Ingredient Search" %>

<h2>Search for More Ingredients</h2>

<div ="fields">
  <%= form_tag(isearch_path, method: :get ) do %>
  <%= text_field_tag :keyword, nil, placeholder: "Find More Ingredients..." %>
  <%= submit_tag %>
  <% end %>
</div>


<ul>

  <table>
    <thead>
      <tr>
        <th colspan="3">Item Name</th>
        <th colspan="3">Description</th>
        <th colspan="3">Calories</th>
      </tr>
    </thead>

    <tbody>
      <% if @results.present? %>
      <% @results.map do |i| %>
      <tr>
        <td><%= i["fields"]["item_name"] %></td>
        <td><%= i["fields"]["item_description"] %></td>
        <td><%= i["fields"]["nf_calories"] %></td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>

app/views/ingredients/show.html.erb
<% content_for :title, @ingredient.name %>

<p id="notice"><%= notice %></p>

<h2><%= @ingredient.name %></h2>
<div class="ingredient-image">
  <%= image_tag(get_image(@ingredient.name), width: "125") %>
</div>
<p><%= @ingredient.body %></p>

<h2>Nutrition Facts</h2>

<% if @facts.empty? %>

<p> Sorry, it looks like we've maxed out the API requests for the day. </p>

<% else %>

<%= render 'nutrition' %>

<% end %>


<% if current_user.admin? %>
<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<% end %>
<%= link_to 'Back', ingredients_path %>