config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :recipes
  resources :ingredients

   root 'pages#home'
   get 'pages/about'

   get '/search', to: 'recipes#search'

end

app/views/layouts/_analytics.html.erb
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-59099331-1', 'auto');
ga('send', 'pageview');

</script>

app/views/layouts/_feed.html.erb
<h2>My Juice Recipes</h2>

<% if current_user.recipes.present? %>
<% @user_recipes.each do |recipe| %>

<div class="juice-container">
  <h3><%= link_to recipe.name, recipe %></h3>
  <%= link_to image_tag(recipe.featured_image_url(:thumb), width: "150px"), recipe, style: "max-width:100%;height:auto;" %>
  <p><%= truncate(recipe.body, lenght: 50) %></p>
</div>
<% end %>

<% elsif @soft_recipes.present? %>
<% @soft_recipes.each do |recipe| %>
<div class="juice-container">
  <h3><%= link_to recipe.name, recipe %></h3>
  <%= link_to image_tag(recipe.featured_image_url(:thumb), width: "150px"), recipe, style: "max-width:100%;height:auto;" %>
  <p><%= truncate(recipe.body, lenght: 50) %></p>
</div>
<% end %>

<% else %>

<p>It looks like you haven't created any Juices yet, why not give it a try? It's fun stuff!</p>

<%= button_to "Create Recipe", new_recipe_path, class: "button-default", method: :get %>

<% end %>

<h2>Popular Juice Recipes</h2>

<% @recipes.each do |recipe| %>

<div class="juice-container">
  <h3><%= link_to recipe.name, recipe %></h3>
  <%= link_to image_tag(recipe.featured_image_url(:thumb), width: "150px"), recipe, style: "max-width:100%;height:auto;" %>
  <p><%= truncate(recipe.body, length: 50) %></p>
</div>

<% end %>

<%= will_paginate @recipes %>

app/views/layouts/_footer.html.erb
<footer>

<div class="footer-content">
JuiceSherpa was created in Seattle, WA. <%= link_to "Build this App from Scratch", "http://codediode.io" %>

</div>


</footer>

app/views/layouts/_ingredient_search.html.erb
<table id="item-table">
  <thead>
    <tr>
      <th>Item Name</th>
      <th>Description</th>
      <th>Calories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @results.present? %>
    <span><% @results.map do |i| %></span>
    <tr>
      <td><%= i["fields"]["item_name"] %></td>
      <td><%= i["fields"]["item_description"] %></td>
      <td><%= i["fields"]["nf_calories"] %></td>
      <td><%= link_to "Add Ingredient", { action: :create, ingredient: { name: i["fields"]["item_name"], item_id: i["fields"]["item_id"] } }, method: :post %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/layouts/_navigation.html.erb
<div class="nav-container">
<nav>
  <ul>
      <li class="nav-logo"><%= image_tag("JuiceSherpa-Logo.svg", height: "40") %></li>
      <div class="nav-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', pages_about_path %></li>
        <li class="explore"><%= link_to 'Explore', '#' %></li>
        <li class="user-menu"><span class="menu-icon"><a href="#">f</a></span></li>
        <li><span class="menu-icon"><%= link_to '(', new_recipe_path %></span></li>
        <li class="search-button"><span class="menu-icon"><a href="#search">s</a></span></li>
      </div>
  </ul>
</nav>
</div>

<nav class="nav-second">
  <ul>
      <li><%= link_to 'Carrots', search_path(keyword: "carrot") %></li>
      <li><%= link_to 'Beets', search_path(keyword: "beet") %></li>
      <li><%= link_to 'Jicama', search_path(keyword: "jicama") %></li>
      <li><%= link_to 'Strawberry', search_path(keyword: "strawberry") %></li>
      <li><%= link_to 'Ginger', search_path(keyword: "ginger") %></li>
      <li><%= link_to 'Tomato', search_path(keyword: "tomato") %></li>
      <li><%= link_to 'Strawberry', search_path(keyword: "kale") %></li>
  </ul>
</nav>

<nav class="nav-third">
  <ul>
    <div class="nav-right">
      <% if current_user.soft_user? %>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% else %>
      <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% end %>
    </div>
  </ul>
</nav>

app/views/layouts/_search.html.erb
<div class="search">
  <%= form_tag(search_path, method: :get ) do %>
  <%= text_field_tag :keyword, nil, placeholder: "Search for a Juice..." %>
  <% end %>
  <div class="close"><a href="">X</a></div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JuiceSherpa | <%= page_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>


  <%= render 'layouts/search' %>
  <%= render 'layouts/navigation' %>

  <div id="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <%= yield %>

  </div>

  <%= render 'layouts/footer' %>
  <%= render 'layouts/analytics' %>


</body>
</html>